### ISSUE TITLE
Nespresso Vertuo Next

### ISSUE THREAD

**Issue by isaaccs** [tritter/homebridge-brewer#5]
Hi,

is it compatible with the vertuo next ?

**Comment by tritter** [comment]
It seems to be impossible. I haven't enough time to try all available bluetooth commands, but it seems like the whole button isn't exposed as interface. (Also the Nespresso app doesn't have a button to do so unfortunately)

**Comment by rgreco87** [comment]
Hi there.
Nespresso Vertuo Next coffee machine has both Bluetooth and WiFi connections.

So, is it possible to add it to HomeBridge since it's connected to my WiFi network?

**Comment by tritter** [comment]
Hi @xazac,

Unfortunately it is not possible to brew coffee using Bluetooth/Wifi and the Vuerto Next. I also don't understand the decision (also not possible using the Nespresso app). Probably because the new capsules can't stay fresh (as they are punctuated when you close the machine).

The only thing you can read is the descaling option, which isn't satisfying.
